### ISSUE TITLE
Redshift extraction failing on DDL exceeding 64k in length

### ISSUE THREAD

**Issue by sfc-gh-dcole** [MobilizeNet/SnowConvertDDLExportScripts#29]
Customer attempting to extract Redshift procedure DDL experiences the following error:

![image](https://user-images.githubusercontent.com/88164052/163013363-3ab703d6-f7c1-4612-8494-00177b756b2e.png)

Retooling the extractor to obtain and iterate over procedure(argument) signatures, then execute "show procedure $signature" may overcome the varchar limitation imposed by the SQL statement

**Comment by jchaconbogarin-mb** [comment]
Hello, @sfc-gh-dcole. Thanks for pointing this out. The alternative you propose seems to be working. We'll have a release for a fix by Monday since this requires some iteration and a big number of validations since all `SHOW` statements need to be executed individually and that might rise some other issues with concurrency.

**Comment by jchaconbogarin-mb** [comment]
Hello @sfc-gh-dcole, we've pushed a folder with an alternative solution, which will execute the `SHOW PROCEDURE $signature` in batches and it will also make a controlled execution of these to avoid concurrency issues on Redshift.

**Comment by sfc-gh-dcole** [comment]
Greetings - customer had unknown issues with the python alternative that unfortunately led to a missed engagement.

Bob Maglies (@sfc-gh-bmaglies) has offered up a pure SQL alternative that appears to completely extract procedures with DDL > 64k.

Please grant Bob access to this repo, refer to the code attached, and reach out to Bob and/or I with further questions.  If acceptable, would like to see this published asap.

[Redshift_SP_extract.txt](https://github.com/MobilizeNet/SnowConvertDDLExportScripts/files/8772286/Redshift_SP_extract.txt)

**Comment by orellabac** [comment]
Hi. @sfc-gh-bmaglies just needs to fork this repo make any changes and send a PR. We will handle the merge request

**Comment by jchaconbogarin-mb** [comment]
Hello @sfc-gh-dcole, the change has already been applied. Thanks @sfc-gh-bmaglies for the contribution!
