### ISSUE TITLE
DDL chunk is truncated for long DDL statements during extraction.

### ISSUE THREAD

**Issue by ksiddiqui79** [MobilizeNet/SnowConvertDDLExportScripts#34]
DDL chunk is truncated for long DDL statements during extraction while spooling multiple DDL statements.
We should increase values for `LONG` and `LONGCHUNKSIZE` to max in "`create_ddl.sql`" (like below):
```
SET LONG 2000000000
SET LONGCHUNKSIZE 200000000
```

**Comment by orellabac** [comment]
I just applied this change
