### ISSUE TITLE
SQL Server extractor skipping database names containing spaces

### ISSUE THREAD

**Issue by sfc-gh-dcole** [MobilizeNet/SnowConvertDDLExportScripts#35]

**Comment by sfc-gh-dcole** [comment]
@orellabac hi I have a fix for this but am unable to push to your repo (as I could before)...  Please advise

**Comment by orellabac** [comment]
@sfc-gh-dcole 
The approach is to do a fork and then from the forked repo send the PR. If you still have issue, maybe just upload the changed files and we will commit the fixed

**Comment by orellabac** [comment]
It is merge now. I had an issue with the initial conflict resolution but it is fixed now.
