### ISSUE TITLE
SQL Server support for PowerShell 7 on windows, pwsh on mac

### ISSUE THREAD

**Issue by sfc-gh-dcole** [MobilizeNet/SnowConvertDDLExportScripts#37]
Have had several instances now where customers are attempting to execute the script in PowerShell 7 on Windows.  I've taken the liberty of coding support for same.  As a bonus, I believe the script now also executes via pwsh on MacOS.  Please see pushed code and test before deploying?  Thanks!

**Comment by sfc-gh-dcole** [comment]
Code is pushed here[https://github.com/sfc-gh-dcole/SnowConvertDDLExportScripts/tree/main/SQLServer](url)

**Comment by sfc-gh-dcole** [comment]
Revised to v2.9 - please review/test/incorporate asap.  Thanks!

**Comment by orellabac** [comment]
@sfc-gh-dcole  updated with that branch. But it says v2.8 is that correct ?
